# Generated by Django 5.0.6 on 2025-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpropagation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='etiqueta',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
