# Generated by Django 5.0.6 on 2025-02-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpropagation', '0002_usuario_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='backpropagation.usuario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table='cuentas',
        ),
    ]
