# Generated by Django 5.0.6 on 2025-02-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpropagation', '0003_alter_comentario_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='username',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
